USE [master]
GO

/****** Object:  Database [Quiz1]    Script Date: 11/23/2022 5:59:08 PM ******/
CREATE DATABASE [Quiz1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Quiz1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Quiz1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Quiz1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Quiz1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Quiz1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Quiz1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Quiz1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Quiz1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Quiz1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Quiz1] SET ARITHABORT OFF 
GO

ALTER DATABASE [Quiz1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Quiz1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Quiz1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Quiz1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Quiz1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Quiz1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Quiz1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Quiz1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Quiz1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Quiz1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Quiz1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Quiz1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Quiz1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Quiz1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Quiz1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Quiz1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Quiz1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Quiz1] SET RECOVERY FULL 
GO

ALTER DATABASE [Quiz1] SET  MULTI_USER 
GO

ALTER DATABASE [Quiz1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Quiz1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Quiz1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Quiz1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Quiz1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Quiz1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Quiz1] SET  READ_WRITE 
GO


USE [Quiz1]
GO

/****** Object:  Table [dbo].[ToDo]    Script Date: 11/23/2022 5:59:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ToDo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[Due] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO